// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/dashboard.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/person/[id].ts";
import * as $5 from "./routes/person/index.ts";
import * as $6 from "./routes/position/[id].ts";
import * as $7 from "./routes/position/index.ts";
import * as $$0 from "./islands/SelectedPersonProvider.tsx";
import * as $$1 from "./islands/drawer/drawer.tsx";
import * as $$2 from "./islands/people/people.tsx";
import * as $$3 from "./islands/person/person-styles.ts";
import * as $$4 from "./islands/person/person.tsx";
import * as $$5 from "./islands/position/position-styles.ts";
import * as $$6 from "./islands/position/position.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/dashboard.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/person/[id].ts": $4,
    "./routes/person/index.ts": $5,
    "./routes/position/[id].ts": $6,
    "./routes/position/index.ts": $7,
  },
  islands: {
    "./islands/SelectedPersonProvider.tsx": $$0,
    "./islands/drawer/drawer.tsx": $$1,
    "./islands/people/people.tsx": $$2,
    "./islands/person/person-styles.ts": $$3,
    "./islands/person/person.tsx": $$4,
    "./islands/position/position-styles.ts": $$5,
    "./islands/position/position.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
