// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/auth/index.ts";
import * as $3 from "./routes/dashboard.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/person/[id].ts";
import * as $7 from "./routes/person/index.ts";
import * as $8 from "./routes/position/[id].ts";
import * as $9 from "./routes/position/index.ts";
import * as $$0 from "./islands/drawer/drawer-styles.ts";
import * as $$1 from "./islands/drawer/drawer.tsx";
import * as $$2 from "./islands/login-island/login-island.tsx";
import * as $$3 from "./islands/people/people.tsx";
import * as $$4 from "./islands/person/SelectedPersonProvider.tsx";
import * as $$5 from "./islands/person/person-styles.ts";
import * as $$6 from "./islands/person/person.tsx";
import * as $$7 from "./islands/person/selectedPerson.ts";
import * as $$8 from "./islands/position/position-styles.ts";
import * as $$9 from "./islands/position/position.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/auth/index.ts": $2,
    "./routes/dashboard.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/person/[id].ts": $6,
    "./routes/person/index.ts": $7,
    "./routes/position/[id].ts": $8,
    "./routes/position/index.ts": $9,
  },
  islands: {
    "./islands/drawer/drawer-styles.ts": $$0,
    "./islands/drawer/drawer.tsx": $$1,
    "./islands/login-island/login-island.tsx": $$2,
    "./islands/people/people.tsx": $$3,
    "./islands/person/SelectedPersonProvider.tsx": $$4,
    "./islands/person/person-styles.ts": $$5,
    "./islands/person/person.tsx": $$6,
    "./islands/person/selectedPerson.ts": $$7,
    "./islands/position/position-styles.ts": $$8,
    "./islands/position/position.tsx": $$9,
  },
  baseUrl: import.meta.url,
};

export default manifest;
